services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: sonalkhare
      WORDPRESS_DB_PASSWORD: sonalkhare123
      WORDPRESS_DB_NAME: sonaldb
    volumes:
      - wordpress:/var/www/html

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: sonaldb
      MYSQL_USER: sonalkhare
      MYSQL_PASSWORD: sonalkhare123
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db: